---
- name: configure web
  hosts: web
  remote_user: rusik
  become: yes
  vars_files:
    - group_vars/web.yml
  roles:
    - web

- name: configure db
  hosts: db
  remote_user: rusik
  become: yes
  vars_files:
    - group_vars/db.yml
  roles:
    - db